service: serverless-flask

plugins:
  - serverless-python-requirements
  - serverless-wsgi

package:
  exclude: 
    - node_modules/**
    - .serverless/serverless-flask.zip.zip
    - serverless.yml
    - yarn.lock

custom:
  wsgi:
    app: app.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: non-linux

provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: us-east-1

functions:
  app:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
